Ecommerce_App/website/views.py
from flask import Blueprint, flash, redirect, render_template, request,session, url_for
from . import conn
import uuid
import datetime
from uuid import uuid4
# from inventory import inventoryfun

views = Blueprint('views',__name__)
db = conn.connection()

@views.route('/')
def home():
    print("Inside View.Home")
    documents = db.products.find()
    products = [{item: data[item] for item in data if item != '_id'} for data in documents]
    return render_template("home.html",products=products)


@views.route('/add',methods=["GET", "POST"])
def addToCart():
    print("Inside View.Add to cart")
    if(session['name']):
        temp=request.args
        temp=temp.to_dict(flat=False)
        pid=temp["pid"][0]
        qty=temp["qty"][0]
        if (pid in session["cart"]):
            idx = session["cart"].index(pid)
            session["qty"][idx]=str(int(qty)+int(session["qty"][idx])) 
            print("qNew Quantity si ",session["qty"])
            documents = db.products.find()
            products = [{item: data[item] for item in data if item != '_id'} for data in documents]
            return render_template("home.html",products=products)
        qty=temp["qty"][0]
        product = db.products.find_one({'item_id':int(pid)})
        if product['Quantity']<int(qty):
            flash('Item Out of Stock',category='error')
            documents = db.products.find()
            products = [{item: data[item] for item in data if item != '_id'} for data in documents]
            return render_template("home.html",products=products)
        else:
            session["cart"].append(pid)
            session["qty"].append(qty)
      
        documents = db.products.find()
        products = [{item: data[item] for item in data if item != '_id'} for data in documents]
        return render_template("home.html",products=products)

@views.route('/remove')
def remove():
    print("Inside View.remove to cart")
    if(session['name']):
        temp=request.args
        temp=temp.to_dict(flat=False)
  
        item_id=temp["itemid"][0]

        idx=session["cart"].index(item_id)
        session["cart"].pop(idx)
        session["qty"].pop(idx)

    return redirect(url_for('views.viewCart'))

@views.route('/payment')
def payment():
    print("Inside Payment Function ")
    order_id=uuid.uuid4()
    payment_id=uuid.uuid4()
    email_id = session["name"]
    status=True
    payment_type=request.form.get('cardtype')
    session['paymentType']=payment_type
    shipping_address={}
    #shipping Address
    if payment_type== "cash":
        status=False
    if status==True:
        user = db.customers.find_one({"email":email_id})
        shipping_address=user['shipping_address']
        # print("----------------",shipping_address['Street1'])
        payment_details=user['payment_details']
        # order Table details 
        print(order_id,payment_id,email_id,payment_type,shipping_address['country'])
        # flash('Login Successfull!!',category='success')
        return render_template("payment.html",shippingAddress=shipping_address,paymentDetails=payment_details,status=status)
    else:
        user = db.customers.find_one({"email":email_id})
        shipping_address=user['shipping_address']
        payment_details=user['payment_details']
        time = datetime.datetime.now()
        return render_template("payment.html",shippingAddress=shipping_address,paymentDetails=payment_details,status=status)


@views.route('/updatepayment')
def paymentdone():
    order_id=str(uuid.uuid4())
    payment_id=str(uuid.uuid4())
    email_id = session["name"]
    status=True
    payment_type=session['paymentType']
    session['paymentType']=None
    payment_type="credit"
    shipping_address={}
    if payment_type== "Cash":
        status=True
    if status==True:
        user = db.customers.find_one({"email":email_id})
        shipping_address=user['shipping_address']
        payment_details=user['payment_details']
        time = datetime.datetime.now()
        products=[]
        cartslist=session["cart"]
        qtylist=session["qty"]
        finalprice=0
        item_details=[]
        for i in range(len(cartslist)):
            print("index of ..",)
            data = db.products.find_one({'item_id':int(cartslist[i])})
            dbquantity = int(data['Quantity'])-int(qtylist[i])
            db.products.update_one({'item_id':int(cartslist[i])}, { "$set": { "Quantity": int(dbquantity) } } )
            temp=round(float(data['price'])*int(qtylist[i]),2)
            finalprice+=temp
            products.append({'item_id':data['item_id'],'title':data['title'],'price':float(data['price']),'qty':int(qtylist[i]),'subtotalprice':temp})
            individual_item={
                "item_id": data['item_id'],
                "qty": int(qtylist[i]),
                "discount": 0.0,
                "price": float(data['price']),
                "category": data['category']
            }
            item_details.append(individual_item)
        tax= round(finalprice*0.09,2)
        total_price_tax=round(finalprice+tax,2)
        payment_status = "successfull"
        input_data =  {
            "order_id": order_id,
            "payment_id": payment_id,
            "email_id": email_id,
            "payment_type": payment_type,
            "shippingAddress": shipping_address,
            "payment_details": payment_details,
            "time_payment": time,
            "total_price_tax": total_price_tax,
            "payment_status": payment_status
            }
        db.payment.insert_one(input_data)
        data = {
        "order_id": order_id,
        "item_details": item_details,
        "email_id": email_id,
        "total_price": total_price_tax,
        "order_status": "Delivered",
        "time_order": time
        }
        db.orders.insert_one(data)
        session["cart"]=[]
        session["qty"]=[]
        session["paymentType"]=None
        flash(' Order Placed!!',category='success')
        return redirect(url_for('views.home'))
    return render_template("payment.html")

@views.route('/cart')
def viewCart():
    print("Inside View.viewCart")
    products=[]
    cartslist=session["cart"]
    qtylist=session["qty"]
    finalprice=0
    for i in range(len(cartslist)):
        print("index of ..",)
        data = db.products.find_one({'item_id':int(cartslist[i])})
        temp=round(float(data['price'])*int(qtylist[i]),2)
        finalprice+=temp
        products.append({'item_id':data['item_id'],'title':data['title'],'price':float(data['price']),'qty':int(qtylist[i]),'subtotalprice':temp})
    tax= round(finalprice*0.09,2)
    pricewithtax=round(finalprice+tax,2)
    return render_template("cart.html",data=products,finalprice=round(finalprice,2),tax=tax,pricewithtax=pricewithtax)


@views.route('/orders')
def Orders():

    print("Inside myorder page ")
    documents = db.orders.find({'email_id':session["name"]})
    orders = [{item: data[item] for item in data if item != '_id'} for data in documents]
    print(orders)

    return render_template("orders.html",data=orders)

@views.route('/viewOrders',methods=["GET", "POST"])
def viewOrders():
    print("Inside viewOrders page ")
    temp=request.args
    temp=temp.to_dict(flat=False)
    orderid=temp["orderid"][0]
    singleorder = db.orders.find_one({'order_id':orderid})
    orderid=singleorder['order_id'] 
    temp={}
    orderdata=[]
    for item in singleorder['item_details']:
        print(item['item_id'])
        product = db.products.find_one({'item_id':item['item_id']})
        title = product['title']
        category= item['category']
        returnid = str(singleorder['order_id'])+","+str(item['item_id'])
        price=item['price']
        quantity=item['qty']
        temp={
        "orderid":singleorder['order_id'],
        "emailid": singleorder['email_id'],
        "totalprice":singleorder['total_price'],
        "status":singleorder['order_status']
        }   
        temp["title"]=title
        temp["category"]=category
        temp["returnid"]=returnid
        temp["price"]=price
        temp["quantity"]=quantity
        print("Before Adding ....")
        print(temp)
        orderdata.append(temp)
        temp={}
    return render_template("viewOrder.html",data=orderdata)

@views.route('/returns',methods=["GET", "POST"])
def returns():
    print("Inside Returns Function")
    temp=request.args
    temp=temp.to_dict(flat=False)
    returnid=temp["returnid"][0]
    li=returnid.split(',')
    orderid= li[0]
    itemid=li[1]
    item= db.orders.find_one({'order_id':orderid})
    print("return_id inside the returns fucntion is",returnid)
    #  To check if it is present in the return table 
    return_item= db.returns.find_one({'return_id':returnid})
    print(return_item)
    print("+++++++++++++++++++++++++++++")
    # print(return_item["item_id"])
    # if int(return_item["item_id"])==int(itemid):
    if return_item!=None:
        flash(' This Item is Already Returned',category='error')
        return redirect(url_for('views.Orders'))
    # if(item["order_status"]!="Delivered"):
    #     flash(' This Item is Already Returned',category='error')
    #     return redirect(url_for('views.Orders')) 
    
    ordered_time = item["time_order"]
    items= item["item_details"]
    temp={}
    for i in items: 
        print(i['item_id'])
        if str(i['item_id'])==str(itemid):
            temp['qty']=i['qty']
            temp['discount']=i['discount']
            temp['price']=i['price']
            temp['category']=i['category']
    if(temp["category"] in ["vegetables","diary"]):
        current_time = datetime.datetime.now()
        duration = current_time - ordered_time

Ecommerce_App/website/templates/allorders.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% block content %}

        <head>
            <style>
                .cart-page{
                    margin: 80px auto;
                }
                table{
                    width:100%;
                    border-collapse: collapse;
                }
                .cart-info{
                    display: flex;
                    flex-wrap: wrap;
                }
                th{
                    text-align: left;
                    padding:5px;
                    color:#fff;
                    background:#ff523b;
                    font-weight: normal;
                }
                td{
                    padding: 10px 5px;
                }
                td input{
                    width: 40px;
                    height: 30px;
                    padding: 5px;
                }
                td a{
                    color:#ff523b;
                    font-size: 12px;
                }
                td img{
                    width: 80px;
                    height: 80px;
                    margin-right: 10px;
                }

                .total-price{
                    display: flex;
                    justify-content: flex-end;
                }

                .total-price table{
                    border-top: 3px solid #ff523b;
                    width:100%;
                    max-width: 400px;
                }

                td:last-child{
                    text-align:right;
                }
                th:last-child{
                    text-align:right;
                }
                #footerback{
                    text-align:right;
                }
            </style>
        </head>
        <div class ="small-container cart-page">
            <table>
                <tr>
                    <th>SNO</th>
                    <th>Order_Id</th>
                    <th>Time</th>
                    <th>user</th>
                    <th>items</th>
                    
                </tr>
                <form action="{{url_for('views.viewOrders')}}" methods="POST">
                {% for order in data %} 
                
                <tr>
                    <td>
                        <div class="cart-info">
                            <!-- <img src="images/product-item1.jpg" alt=""> -->
                            <div>
                                <p>{{data.index(order)+1}}</p>
                                
                            </div>
                        </div>
                    </td>
                    <td><p>{{order.order_id}}</p></td>
                    <td>{{order.time_order}}</td>
                    <td>{{order.email_id}}</td>
                    
                    <td>
                        <p>[</p>
                        {% for i in order.item_details %}
                            
                            <p>Item_id:{{i.item_id}}, Quantity:{{i.qty}}</p>
                            
                        {% endfor %}
                        <p>]</p>
                            <!-- <button type="submit" name=orderid id=orderid value={{order.order_id}} class="btn btn-primary"> view Order
                               
                            </button> -->
                            <p>------------------------------------------------------------</p>
                        
                    </td>
                </tr>
               
                
                {% endfor %}

            </form>
            </table>

        <form action="/">
            <button type="submit" value="submit" id="footerback" class="btn btn-primary"> BACK
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>
        </div>


{% endblock %} 

Ecommerce_App/website/templates/cart.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% block content %}

        <head>
            <style>
                .cart-page{
                    margin: 80px auto;
                }
                table{
                    width:100%;
                    border-collapse: collapse;
                }
                .cart-info{
                    display: flex;
                    flex-wrap: wrap;
                }
                th{
                    text-align: left;
                    padding:5px;
                    color:#fff;
                    background:#ff523b;
                    font-weight: normal;
                }
                td{
                    padding: 10px 5px;
                }
                td input{
                    width: 40px;
                    height: 30px;
                    padding: 5px;
                }
                td a{
                    color:#ff523b;
                    font-size: 12px;
                }
                td img{
                    width: 80px;
                    height: 80px;
                    margin-right: 10px;
                }

                .total-price{
                    display: flex;
                    justify-content: flex-end;
                }

                .total-price table{
                    border-top: 3px solid #ff523b;
                    width:100%;
                    max-width: 400px;
                }

                td:last-child{
                    text-align:right;
                }
                th:last-child{
                    text-align:right;
                }
            </style>
        </head>
        <div class ="small-container cart-page">
            <table>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
                
                {% for item in data %} 
                <tr>
                    <td>
                        <div class="cart-info">
                            <!-- <img src="images/product-item1.jpg" alt=""> -->
                            <div>
                                <p>{{item.title}}</p>
                                <small>Price: {{item.price}}</small>
                                <br>
                                <!-- <a href="">Remove</a> -->
                                <form action="{{url_for('views.remove')}}" methods="POST">
                                    <button type="submit" name=itemid id=itemid value={{item.item_id}} class="btn btn-primary"> Remove
                                    </button>
                                </form>
                            </div>
                        </div>
                    </td>
                    <td><input type="number" value={{item.qty}}></td>
                    <td>$ {{item.subtotalprice}}</td>
                </tr>
               
                
                {% endfor %}

                <!-- <tr>
                    <td>
                        <div class="cart-info">
                            <img src="images/buy-1.jpg" alt="">
                            <div>
                                <p>Product Title here</p>
                                <small>Price: $50.00</small>
                                <br>
                                <a href="">Remove</a>
                            </div>
                        </div>
                    </td>
                    <td><input type="number" value="1"></td>
                    <td>$ 50.00</td>
                </tr>
                

                <tr>
                    <td>
                        <div class="cart-info">
                            <img src="images/buy-1.jpg" alt="">
                            <div>
                                <p>Product Title here</p>
                                <small>Price: $50.00</small>
                                <br>
                                <a href="">Remove</a>
                            </div>
                        </div>
                    </td>
                    <td><input type="number" value="1"></td>
                    <td>$ 50.00</td>
                </tr>
                 -->

            </table>

        <div class="total-price">
            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>${{finalprice}}</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>${{tax}}</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>${{pricewithtax}}</td>
                </tr>
            </table>
        </div>
        <form action="/payment">
            <button type="submit" value="submit" class="btn btn-primary"> Delivery Order
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>
        <br>
        <form action="/">
            <button type="submit" value="submit" id="footerback" class="btn btn-primary"> BACK
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>

        <br>
        <form action="/updatepayment">
            <button type="submit" value="submit" id="footerback" class="btn btn-primary"> Pick up on delivery
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>
        </div>








































{% endblock %} 

Ecommerce_App/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

              <head>
                <style>
                  .row {
    margin-top :100px;
}

.btn{
    width: 100%;
}

.btn button {
    width: 100%;
    border-radius:5px;
    border:none;
    letter-spacing: 2px;
    font-weight: bold;
    margin-top:6px;
    cursor:pointer;
}

.btn i img{
    margin-bottom:3px;
}
.card{
    box-shadow: 0px 2px 5px black;
    transition: transform 0.5s;
    cursor: pointer;
}

.card:hover{
    transform:translateY(-15px);
}

.star{
    font-size:20px;
}
.checked{
    color:rgba(255, 196, 0)
}



                </style>
              </head>
    <div class="container">
        <div class="row">
          
            {%for data in products %}
           
            
            <div class="col-md-3">
              <form action="{{url_for('views.addToCart')}}" methods="POST"> 
                <div class="card">
                    <img class="card-image-top" src="buy-2.jpg" alt="">
                    <div class="card-body">
                        <h2 class="card-title text-center">{{ data['title'] }}</h2>
                        <p class="card-text text-center">{{data['Description']}}</p>
                        <h5 class="text-center">${{data['price']}}</h5>
                        <div class="star text-center">
                            <i class="fa fa-star checked"></i>
                            <i class="fa fa-star checked"></i>
                            <i class="fa fa-star checked"></i>
                            <!-- <i class="fa fa-star checked"></i>
                            <i class="fa fa-star checked"></i> -->
                        </div>
                        
                        <h5>Qty :</h5>
                        <input type="number" name="qty" id ="qty" value="1">
                        <div class="btn">
                            <!-- <input type="submit" name="itemid" value="{{data['item_id']}}">  -->
                            <button type="submit" id="pid" name="pid" value="{{data['item_id']}}">Add<i><img src="cart-add.png" alt=""></img></i></button>
                            <!-- <a href="/add" value="{{data['item_id']}}"></a> -->
                        </div>
                    </div>
                </div>
              </form>
            </div>
            
            {% endfor %}



            
              
            
                       

            
        </div>
    </div>
{% endblock %} 

Ecommerce_App/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}


<form action="/login" method="POST">
    <h3 align="center">Login</h3>

    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/> 
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"/> 
    </div>

    <!-- <div class="form-group">
        <label for="type">Customer Type</label>
        <input type="" class="form-control" id="password" name="password" placeholder="Enter password"/> 
    </div> -->
    <div class="control-group">
        <label class="control-label">Account Type</label>
        <div class="controls">
            <select id="account" name="account">
                <option value="customer" selected>Customer</option>
                <option value="admin">Admin</option>
              </select>
        </div>
    </div>

    <br/>
<button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %} 

Ecommerce_App/website/templates/orders.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% block content %}

        <head>
            <style>
                .cart-page{
                    margin: 80px auto;
                }
                table{
                    width:100%;
                    border-collapse: collapse;
                }
                .cart-info{
                    display: flex;
                    flex-wrap: wrap;
                }
                th{
                    text-align: left;
                    padding:5px;
                    color:#fff;
                    background:#ff523b;
                    font-weight: normal;
                }
                td{
                    padding: 10px 5px;
                }
                td input{
                    width: 40px;
                    height: 30px;
                    padding: 5px;
                }
                td a{
                    color:#ff523b;
                    font-size: 12px;
                }
                td img{
                    width: 80px;
                    height: 80px;
                    margin-right: 10px;
                }

                .total-price{
                    display: flex;
                    justify-content: flex-end;
                }

                .total-price table{
                    border-top: 3px solid #ff523b;
                    width:100%;
                    max-width: 400px;
                }

                td:last-child{
                    text-align:right;
                }
                th:last-child{
                    text-align:right;
                }
                #footerback{
                    text-align:right;
                }
            </style>
        </head>
        <div class ="small-container cart-page">
            <table>
                <tr>
                    <th>SNO</th>
                    <th>Tracking Id</th>
                    <th>Order Status</th>
                    <th>Time</th>
                    <th>Details</th>
                </tr>
                <form action="{{url_for('views.viewOrders')}}" methods="POST">
                {% for order in data %} 
                <tr>
                    <td>
                        <div class="cart-info">
                            <!-- <img src="images/product-item1.jpg" alt=""> -->
                            <div>
                                <p>{{data.index(order)+1}}</p>
                                
                            </div>
                        </div>
                    </td>
                    <td><p>{{order.order_id}}</p></td>
                    <td>{{order.order_status}}</td>
                    <td>{{order.time_order}}</td>
                    <td>
                    
                            <button type="submit" name=orderid id=orderid value={{order.order_id}} class="btn btn-primary"> view Order
                               
                            </button>
                        
                    </td>
                </tr>
               
                
                {% endfor %}

            </form>
            </table>

        <form action="/">
            <button type="submit" value="submit" id="footerback" class="btn btn-primary"> BACK
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>
        </div>


{% endblock %} 

Ecommerce_App/website/templates/viewOrder.html
{% extends "base.html" %}
{% block title %}view Order{% endblock %}
{% block content %}

        <head>
            <style>
                .cart-page{
                    margin: 80px auto;
                }
                table{
                    width:100%;
                    border-collapse: collapse;
                }
                .cart-info{
                    display: flex;
                    flex-wrap: wrap;
                }
                th{
                    text-align: left;
                    padding:5px;
                    color:#fff;
                    background:#ff523b;
                    font-weight: normal;
                }
                td{
                    padding: 10px 5px;
                }
                td input{
                    width: 40px;
                    height: 30px;
                    padding: 5px;
                }
                td a{
                    color:#ff523b;
                    font-size: 12px;
                }
                td img{
                    width: 80px;
                    height: 80px;
                    margin-right: 10px;
                }

                .total-price{
                    display: flex;
                    justify-content: flex-end;
                }

                .total-price table{
                    border-top: 3px solid #ff523b;
                    width:100%;
                    max-width: 400px;
                }

                td:last-child{
                    text-align:right;
                }
                th:last-child{
                    text-align:right;
                }
            </style>
        </head>
        <div class ="small-container cart-page">
            <table>
                <tr>
                    <th>TRACKING</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Status</th>
                    <!-- <th>Cancel</th> -->
                    <th>Return</th>
                </tr>
                <form action="{{url_for('views.returns')}}" methods="POST">
                {% for item in data %} 
                <tr>
                    <!-- <td>
                        <p>{{item.item_id}}</p>
                                            
                    </td> -->

                    
                    <td>
                        <div class="cart-info">
                            <!-- <img src="images/product-item1.jpg" alt=""> -->
                            <div>
                                <p>{{item.returnid}}</p>
                                
                            </div>
                        </div>
                    </td>
                    <td>
                        <div>
                            <p>{{item.title}}</p>
                            
                        </div>
                    </td>
                    <td><input type="number" value={{item.quantity}}></td>
                    <td>$ {{item.price}}</td>
                    <td>{{item.status}}</td>
                    <td>
                    
                        <button type="submit" name=returnid id=returnid value={{item.returnid}} class="btn btn-primary"> Return
                           
                        </button>
                    
                    </td>
                </tr>
               
                
                {% endfor %}
                

            </form>

            
            </table>
<!-- 
        <div class="total-price">
            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>${{finalprice}}</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>${{tax}}</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>${{pricewithtax}}</td>
                </tr>
            </table>
        </div> -->
        
        </div>
        <form action="/">
            <button type="submit" value="submit" id="footerback" class="btn btn-primary"> BACK
                <!-- <a href="/payment"> Order</a> -->
            </button>
        </form>
{% endblock %} 